# Generated by Django 6.0.3 on 2026-03-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Admin/Manager', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=50),
        ),
    ]
