# Generated by Django 6.0.2 on 2026-02-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period_start', models.DateField()),
                ('payroll_period_end', models.DateField()),
                ('total_regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_late_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_undertime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollEmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, default='', max_length=50)),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_profile', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_period_start', models.DateField()),
                ('payroll_period_end', models.DateField()),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_finalized', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AdjustmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjustment_type', models.CharField(default='Manual', max_length=50)),
                ('justification', models.TextField(blank=True, default='')),
                ('admin_id', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computations.payrollrecord')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'payroll_period_start', 'payroll_period_end'), name='uniq_payrollrecord_employee_period'),
        ),
    ]
