# Generated by Django 6.0.2 on 2026-02-26 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_hired', models.DateField(default=datetime.date.today)),
                ('job_title', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Admin/Manager', 'Admin'), ('Manager', 'Manager'), ('Staff', 'Staff')], max_length=50)),
                ('salary_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('password_hash', models.CharField(max_length=255)),
                ('must_change_password', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
