# Generated by Django 6.0.2 on 2026-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('success_count', models.IntegerField()),
                ('error_count', models.IntegerField()),
                ('status', models.CharField(default='Completed', max_length=50)),
            ],
        ),
    ]
